// The vectors the Agent CLI (packages/cli-go/solana/txcheck), the MCP server
// (packages/mcp) and this page must all decide the same way. The file is
// generated by the CLI's tests and copied here unchanged; see its "about".

import { describe, it, expect } from 'vitest';
import { base58Decode } from '../src/lib/base58';
import { checkTransferMessage, TransactionMismatchError } from '../src/lib/verify-transaction';
import vectors from './txcheck-vectors.json';

interface Vector {
  name: string;
  message: string;
  wallet: string;
  network: string;
  recipient: string;
  min_amount: string;
  max_amount: string;
  max_fee: string;
  sign: boolean;
}

function check(v: Vector): void {
  checkTransferMessage(Uint8Array.from(atob(v.message), c => c.charCodeAt(0)), base58Decode(v.wallet), {
    network: v.network,
    recipient: v.recipient,
    minAmount: BigInt(v.min_amount),
    maxAmount: BigInt(v.max_amount),
    maxFee: BigInt(v.max_fee),
  });
}

describe('shared Key 1 check vectors', () => {
  const all: Vector[] = vectors.vectors;

  it('has the server shapes and the refusals', () => {
    expect(all.filter(v => v.sign).length).toBeGreaterThan(20);
    expect(all.filter(v => !v.sign).length).toBeGreaterThan(40);
  });

  for (const v of all) {
    it(`${v.sign ? 'signs' : 'refuses'}: ${v.name}`, () => {
      if (v.sign) {
        expect(() => check(v)).not.toThrow();
      } else {
        expect(() => check(v)).toThrow(TransactionMismatchError);
      }
    });
  }
});
